language: cpp
cache: ccache
cache:
  directories:
  - /home/travis/_install
os: linux

addons:
  apt:
    sources: &base_sources
      - ubuntu-toolchain-r-test
      - boost-latest
      - kubuntu-backports
    sources: &clang_sources
      - llvm-toolchain-trusty-5.0
    packages: &base_packages
    - libeigen3-dev
    - libboost1.55-all-dev
    - libblas-dev
    - liblapack-dev
    - libtbb-dev
    - cmake
    - cmake-data
    - lcov

env:
  global:
    - BUILD_PREFIX=/home/travis/_build
    - INSTALL_PREFIX=/home/travis/_install

branches:
  only:
  - master

matrix:
  fast_finish: true
  include:
    - compiler: gcc
      env: GCC_VERSION=5 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
           - *base_sources
          packages:
           - *base_packages
           - g++-5
           - gfortran-5
    - compiler: gcc
      env: GCC_VERSION=5 BUILD_TYPE=Release
      addons:
        apt:
          sources:
           - *base_sources
          packages:
           - *base_packages
           - g++-5
           - gfortran-5
    - compiler: gcc
      env: GCC_VERSION=6 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
           - *base_sources
          packages:
           - *base_packages
           - g++-6
           - gfortran-6
    - compiler: gcc
      env: GCC_VERSION=6 BUILD_TYPE=Release
      addons:
        apt:
          sources:
           - *base_sources
          packages:
           - *base_packages
           - g++-6
           - gfortran-6
    - compiler: gcc
      env: GCC_VERSION=7 BUILD_TYPE=Release
      addons:
        apt:
          sources:
           - *base_sources
          packages:
           - *base_packages
           - g++-7
           - gfortran-7
    - compiler: clang
      env: GCC_VERSION=7 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
           - *base_sources
           - *clang_sources
          packages:
           - *base_packages
           - g++-7
           - gfortran-7
           - clang-5.0
    - compiler: clang
      env: GCC_VERSION=7 BUILD_TYPE=Release
      addons:
        apt:
          sources:
           - *base_sources
           - *clang_sources
          packages:
           - *base_packages
           - g++-7
           - gfortran-7
           - clang-5.0
 allow_failures:
     - compiler: gcc
      env: GCC_VERSION=7 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
           - *base_sources
          packages:
           - *base_packages
           - g++-7
           - gfortran-7
           
before_install:
- "env"
- "mkdir -p ${BUILD_PREFIX} && mkdir -p ${INSTALL_PREFIX}"

# use timeout to stop long-running (i.e. cache-rebuilding) jobs right before they get killed by Travis-CI
# in case of timeout report success to Travis to force cache upload
script:
  - travis_wait 115 timeout 6500 ./bin/build-$TRAVIS_OS_NAME.sh;  RESULT=$?; if [ $RESULT -eq 0 ] || [ $RESULT -eq 124 ]; then true; else false; fi;

after_failure:
- cat ${BUILD_PREFIX}/mpqc4/CMakeFiles/CMakeOutput.log
- cat ${BUILD_PREFIX}/mpqc4/CMakeFiles/CMakeError.log

# codecov
after_success:
  # create report
  - cd ${TRAVIS_BUILD_DIR}
  - if [ "$BUILD_TYPE" = "Debug" ] && [ "$GCC_VERSION" = 5 ]; then lcov --gcov-tool gcov-${GCC_VERSION} --directory ${BUILD_PREFIX}/mpqc4 --capture --output-file coverage.info; fi; # capture coverage info
  - if [ "$BUILD_TYPE" = "Debug" ] && [ "$GCC_VERSION" = 5 ]; then lcov --remove coverage.info '/usr/*' '*/tiledarray/*' '*/madness/*' '*/btas/*' '*/tests/*' --output-file coverage.info; fi; # filter out non-project files
  - if [ "$BUILD_TYPE" = "Debug" ] && [ "$GCC_VERSION" = 5 ]; then lcov --list coverage.info; fi; #debug info
  # upload report to CodeCov
  - if [ "$BUILD_TYPE" = "Debug" ] && [ "$GCC_VERSION" = 5 ]; then bash <(curl -s https://codecov.io/bash) -t 91e770bd-4741-4553-a7d3-c226fb4e41fa; fi;

notifications:
  slack:
    secure: aTBPnV/QUvD5zjB82Gz8MwqtjDcxMuAtGY3m2KM4kD54kxZxPXGC7sHb9e/EOHm0qoudTR8aielY99y9mPH3v/5qXvyQKU3md+aE9i+XB2ewm5WXDUXmr8wS63W+9EflXfFeC1JxantyYkZ9n4itCZP7WlY9x7rMfs/+1P5A0Ew=
